services:
  app:
    image: agent-artificial/translation-frontend:dev
    build:
      context: .
    ports:
      - "5757:5757"
    volumes:
      - ./static:/app/static
    environment:
      - ENV=development
