version: '3.8'

services:
  app:
    image: Agent-Artificial/translation-frontend:dev
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
    environment:
      - ENV=development
