from fastapi import APIRouter, Request
from fastapi.templating import Jinja2Templates

templates = Jinja2Templates(directory="./templates")

router = APIRouter()


TASK_STRINGS = [
    "speech2text"
    "speech2speech"
    "auto_speech_recognition"
    "text2speech"
    "text2text"
]

SPEECH_LANGUAGES={
    "English": "eng",
    "German": "deu",
    "French": "fra",
    "Hindi": "hin",
    "Italian": "ita",
    #"Japanese": "jpn",
    #"Korean": "kor",
    "Polish": "pol",
    "Portuguese": "por",
    "Romanian": "ron",
    "Russian": "rus",
    "Spanish": "spa",
    "Swedish": "swe",
    "Ukrainian": "ukr",
    "Vietnamese": "vie",
    "-----------": "",
    "Modern Standard Arabic": "arb",
    "Bengali": "ben",
    "Catalan": "cat",
    "Czech": "ces",
    "Mandarin Chinese": "cmn",
    "Welsh": "cym",
    "Danish": "dan",
    "Estonian": "est",
    "Indonesian": "ind",
    "Kannada": "kan",
    "Maltese": "mlt",
    "Dutch": "nld",
    "Western Persian": "pes",
    "Swahili": "swh",
    "Tamil": "tam",
    "Telugu": "tel",
    "Tagalog": "tgl",
    "Thai": "tha",
    "Turkish": "tur",
    "Urdu": "urd",
    "Northern Uzbek": "uzn",
}
TARGET_LANGUAGES = [
    "Select Language",
    "English",
    "Cantonese",
    "French",
    "German",
    "Hindi",
    "Italian",
    #"Japanese",
    #"Korean",
    "Mandarin Chinese",
    "Russian",
    "Spanish",
    "---",
    #"Afrikaans",
    "English",
    "Afrikaans",
    "Amharic",
    "Modern Standard Arabic",
    "Moroccan Arabic",
    "Egyptian Arabic",
    "Assamese",
    "Asturian",
    "North Azerbaijani",
    "Belarusian",
    "Bengali",
    "Bosnian",
    "Bulgarian",
    "Catalan",
    "Cebuano",
    "Czech",
    "Central",
    "Mandarin Chinese",
    "Mandarin Chinese Hant",
    "Welsh",
    "Danish",
    "German",
    "Estonian",
    "Basque",
    "Finnish",
    "French",
    "Nigerian Fulfulde",
    "West Central Oromo",
    "Irish",
    "Galician",
    "Gujarati",
    "Hebrew",
    "Hindi",
    "Croatian",
    "Hungarian",
    "Armenian",
    "Igbo",
    "Indonesian",
    "Icelandic",
    "Italian",
    "Javanese",
    "Japanese",
    "Kamba",
    "Kannada",
    "Georgian",
    "Kazakh",
    "Kabuverdianu",
    "Halh Mongolian",
    "Khmer",
    "Kyrgyz",
    "Korean",
    "Lao",
    "Lithuanian",
    "Luxembourgish",
    "Ganda",
    "Luo",
    "Standard Latvian",
    "Maithili",
    "Malayalam",
    "Marathi",
    "Macedonian",
    "Maltese",
    "Meitei",
    "Burmese",
    "Dutch",
    "Norwegian Nynorsk",
    "Norwegian Bokmål",
    "Nepali",
    "Nyanja",
    "Occitan",
    "Odia",
    "Punjabi",
    "Southern Pashto",
    "Western Persian",
    "Polish",
    "Portuguese",
    "Romanian",
    "Russian",
    "Slovak",
    "Slovenian",
    "Shona",
    "Sindhi",
    "Somali",
    "Spanish",
    "Serbian",
    "Swedish",
    "Swahili",
    "Tamil",
    "Telugu",
    "Tajik",
    "Tagalog",
    "Thai",
    "Turkish",
    "Ukrainian",
    "Urdu",
    "Northern Uzbek",
    "Vietnamese",
    "Xhosa",
    "Yoruba",
    "Cantonese",
    "Colloquial Malay",
    "Standard Malay",
    "Zulu",
]

@router.get("/languages")
async def get_languages(request: Request):
    lines = []
    for option in TARGET_LANGUAGES:
        lines.append(f'<option class="block bg-cyan-200 hover:bg-cyan-400 dark:hover:bg-cyan-700 dark:bg-cyan-600 px-4 py-2 rounded-t whitespace-no-wrap" value=\"{option}\">{option}</option>')
        
    return {"target_languages": "\n".join(lines)}